### ISSUE TITLE
Dates are not validated Properly in Generate Invoice feature [@Edvoid AdminPanel]

### ISSUE THREAD

**Issue by dheerajghub** [rohitcoder/EdVoid-Core-API-Doc#33]
**Description**
After selecting the ``` Last date for payment ``` attribute in ``` Max Date for payment ```attribute even if the date is greater than the last date it is showing an error.

![Screenshot 2019-05-10 at 7 05 02 PM](https://user-images.githubusercontent.com/31991632/57531269-a8547600-7356-11e9-8a64-3a98bbfb4ba9.png)

**Comment by rohitcoder** [comment]
Fixed..... on local env.
