### ISSUE TITLE
ANDROID - Mail History URL is not loading.

### ISSUE THREAD

**Issue by harshdesai2243** [rohitcoder/EdVoid-Core-API-Doc#40]
Mail History URL is keep on loading (with logo of edvoid and a progress bar.) It does not redirect on the other page or next page.

**Comment by rohitcoder** [comment]
Check again, it's working here!

Use this same URL pattern in your webview https://demo.edvoid.com/mail/history?authenticity_token=ff7b02d87940cc3c30cad92b72ae5c67

**Comment by rohitcoder** [comment]
Resolved....
Feel free to reopen this in future

**Comment by harshdesai2243** [comment]
Sure.
